services:
  - type: web
    name: noltek-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 10000
