services:
  - type: web
    name: video-downloader-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend:app
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
