import { format } from 'date-fns';
import { UserProfile, WalletTransaction } from '../types';
import { formatAmount } from './currency';

export type WalletTransactionMeta = {
  title: string;
  counterparty?: string;
};

function escapeXml(value: string) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

export function getWalletTransactionMeta(tx: WalletTransaction): WalletTransactionMeta {
  const isTransferOut = tx.reference?.startsWith('transfer_out:');
  const isTransferIn = tx.reference?.startsWith('transfer_in:');
  const counterparty = isTransferOut || isTransferIn ? tx.reference?.split(':')[1] : undefined;

  if (isTransferOut) return { title: 'Transfer Sent', counterparty };
  if (isTransferIn) return { title: 'Transfer Received', counterparty };
  if (tx.type === 'topup') return { title: 'Add Funds' };
  return { title: 'Withdraw' };
}

export function buildReceiptSvg(profile: UserProfile, tx: WalletTransaction) {
  const meta = getWalletTransactionMeta(tx);
  const receiptNumber = `RCT-${tx.id.slice(0, 8).toUpperCase()}`;
  const amount = formatAmount(tx.amount, tx.currency);
  const createdAt = format(new Date(tx.createdAt), 'PPP p');
  const lines = [
    ['Account Holder', profile.displayName],
    ['Transaction', meta.title],
    ...(meta.counterparty ? [['Counterparty ID', meta.counterparty]] : []),
    ['Status', tx.status],
    ['Method', tx.method],
    ['Date', createdAt],
    ['Wallet Currency', tx.currency],
    ['Transaction ID', tx.id],
    ['User ID', profile.publicId || profile.uid],
    ['Reference', tx.reference || 'N/A'],
  ] as Array<[string, string]>;

  return `
  <svg xmlns="http://www.w3.org/2000/svg" width="1200" height="1600" viewBox="0 0 1200 1600">
    <defs>
      <linearGradient id="hero" x1="0%" y1="0%" x2="100%" y2="100%">
        <stop offset="0%" stop-color="#0f766e" />
        <stop offset="100%" stop-color="#059669" />
      </linearGradient>
      <filter id="shadow" x="-10%" y="-10%" width="120%" height="120%">
        <feDropShadow dx="0" dy="14" stdDeviation="18" flood-color="#0f172a" flood-opacity="0.12" />
      </filter>
    </defs>
    <rect width="1200" height="1600" fill="#f8fafc" />
    <rect x="80" y="72" width="1040" height="1456" rx="40" fill="#ffffff" filter="url(#shadow)" />
    <rect x="80" y="72" width="1040" height="280" rx="40" fill="url(#hero)" />
    <text x="140" y="170" font-family="Arial, sans-serif" font-size="54" font-weight="700" fill="#ffffff">Connect Receipt</text>
    <text x="140" y="232" font-family="Arial, sans-serif" font-size="28" fill="#d1fae5">${escapeXml(receiptNumber)}</text>
    <text x="140" y="430" font-family="Arial, sans-serif" font-size="74" font-weight="800" fill="#0f766e">${escapeXml(amount)}</text>
    ${lines
      .map(
        ([label, value], index) => `
          <g transform="translate(140, ${520 + index * 92})">
            <text font-family="Arial, sans-serif" font-size="20" font-weight="700" fill="#64748b" letter-spacing="1.5">${escapeXml(label.toUpperCase())}</text>
            <text y="42" font-family="Arial, sans-serif" font-size="34" font-weight="700" fill="#0f172a">${escapeXml(value)}</text>
          </g>
        `
      )
      .join('')}
    <rect x="140" y="1360" width="920" height="1" fill="#e2e8f0" />
    <text x="140" y="1420" font-family="Arial, sans-serif" font-size="24" fill="#475569">
      This receipt was generated by Connect and can be saved or shared for your records.
    </text>
  </svg>`;
}

export function downloadReceiptImage(profile: UserProfile, tx: WalletTransaction) {
  const svg = buildReceiptSvg(profile, tx);
  const blob = new Blob([svg], { type: 'image/svg+xml;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = `connect-receipt-${tx.id.slice(0, 8)}.svg`;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}

export async function shareReceiptImage(profile: UserProfile, tx: WalletTransaction) {
  const svg = buildReceiptSvg(profile, tx);
  const file = new File([svg], `connect-receipt-${tx.id.slice(0, 8)}.svg`, { type: 'image/svg+xml' });
  const meta = getWalletTransactionMeta(tx);
  const text = `${meta.title}\n${formatAmount(tx.amount, tx.currency)}\n${format(new Date(tx.createdAt), 'PPP p')}\nReceipt ID: ${tx.id}`;

  try {
    if (navigator.share && navigator.canShare?.({ files: [file] })) {
      await navigator.share({
        title: 'Connect Receipt',
        text,
        files: [file],
      });
      return;
    }

    if (navigator.share) {
      await navigator.share({
        title: 'Connect Receipt',
        text,
      });
      return;
    }

    downloadReceiptImage(profile, tx);
  } catch {
    downloadReceiptImage(profile, tx);
  }
}
